# STOR 120 - Homework 2: Arrays and Tables

**Recommended Reading**: 
* [Data Types](https://www.inferentialthinking.com/chapters/04/Data_Types.html) 
* [Sequences](https://www.inferentialthinking.com/chapters/05/Sequences.html)
* [Tables](https://www.inferentialthinking.com/chapters/06/Tables.html)

For all problems that you must write explanations and sentences for, you **must** provide your answer in the designated space. Moreover, throughout this homework and all future ones, please be sure to not re-assign variables throughout the notebook! For example, if you use `max_temperature` in your answer to one question, do not reassign it later on. 

**Deadline:**

This assignment is due Wednesday, August 31st at 5:00 PM. Late work will penalized as stated in the syllabus.

Directly sharing answers is not okay, but discussing problems with the course staff or with other students is encouraged.

You should start early so that you have time to get help if you're stuck. 

In [2]:
# Don't change this cell; just run it.

import numpy as np
from datascience import *

## 1. Creating Arrays


**Question 1.1.** Make an array called `weird_numbers` containing the following numbers (in the given order):

1. 6
2. the square root of 86
3. -21
4. 3 to the power of 5.4

*Note:* Python lists are different/behave differently than numpy arrays. In STOR 120, we use numpy arrays, so please make an **array**, not a python list if you know how to do so.

<!--
BEGIN QUESTION
name: q1_1
-->

In [10]:
weird_numbers = make_array(6, math.sqrt(86), -21, 3**5.4)
weird_numbers

array([   6.        ,    9.2736185 ,  -21.        ,  377.09847446])

**Question 1.2.** Make an array called `book_title_words` containing the following three strings: `Eats`, `Shoots`, and `and Leaves`.

<!--
BEGIN QUESTION
name: q1_2
-->

In [12]:
book_title_words = make_array("Eats", "Shoots", "and Leaves")
book_title_words

array(['Eats', 'Shoots', 'and Leaves'],
      dtype='<U10')

Strings have a method called `join`.  `join` takes one argument, an array of strings.  It returns a single string.  Specifically, the value of `a_string.join(an_array)` is a single string that's the [concatenation](https://en.wikipedia.org/wiki/Concatenation) ("putting together") of all the strings in `an_array`, **except** `a_string` is inserted in between each string.

**Question 1.3.** Use the array `book_title_words` and the method `join` to make two strings:

1. `Eats, Shoots, and Leaves` (call this one `with_commas`)
2. `Eats Shoots and Leaves` (call this one `without_commas`)

*Hint:* If you're not sure what `join` does, first try just calling, for example, `"foo".join(book_title_words)` .

<!--
BEGIN QUESTION
name: q1_3
-->

In [16]:
with_commas = ",".join(book_title_words)
without_commas = " ".join(book_title_words)

# These lines are provided just to print out your answers.
print('with_commas:', with_commas)
print('without_commas:', without_commas)

with_commas: Eats,Shoots,and Leaves
without_commas: Eats Shoots and Leaves


## 2. Indexing Arrays


These exercises give you practice accessing individual elements of arrays.  In Python (and in many programming languages), elements are accessed by *index*, so the first element is the element at index 0.

*Note:* Please don't use bracket notation when indexing if you know how to (i.e. `arr[0]`), as this can yield different data type outputs than what we will be expecting.

**Question 2.1.** The cell below creates an array of some numbers.  Set `sixth_element` to the sixth element of `some_numbers`.

<!--
BEGIN QUESTION
name: q2_1
-->

In [22]:
some_numbers = make_array(-1, -3, -6, -10, -15, -19, -24, -30)

sixth_element = some_numbers.item(5)
sixth_element

-19

**Question 2.2.** The next cell creates a table that displays some information about the elements of `some_numbers` and their order.  Run the cell to see the partially-completed table, then fill in the missing information (the cells that say "Ellipsis") by assigning `blank_a`, `blank_b`, `blank_c`, and `blank_d` to the correct elements in the table.

<!--
BEGIN QUESTION
name: q2_2
-->

In [26]:
blank_a = "fourth"
blank_b = "sixth"
blank_c = 0
blank_d = 5
elements_of_some_numbers = Table().with_columns(
    "English name for position", make_array("first", "second", "third", blank_a, "fifth", blank_b, "seventh", "eighth"),
    "Index",                     make_array(blank_c, 1, 2, 3, 4, blank_d, 6, 7),
    "Element",                   some_numbers)
elements_of_some_numbers

English name for position | Index | Element
first                     | 0     | -1
second                    | 1     | -3
third                     | 2     | -6
fourth                    | 3     | -10
fifth                     | 4     | -15
sixth                     | 5     | -19
seventh                   | 6     | -24
eighth                    | 7     | -30

**Question 2.3.** You will sometimes want to find the *last* element of an array.  Suppose an array has 1023 elements.  What is the index of its last element?

<!--
BEGIN QUESTION
name: q2_3
-->

In [28]:
index_of_last_element = 1022

More often, you don't know the number of elements in an array, its *length*.  (For example, it might be a large dataset you found on the Internet.)  The function `len` takes a single argument, an array, and returns the `len`gth of that array (an integer).

**Question 2.4.** The cell below loads an array called `primary_total_votes`. This array has the votes for each candidate or ballot choice in every contest held in North Carolina in the May 8, 2018 elections.. Calling `.column(...)` on a table returns an array of the column specified, in this case the `sum_total_votes` column of the `primary_results` table. The last element in the array is the number of votes for Randy Ollis in the election for the Yancey County Board of Commissioners. Assign this number of votes to `Ollis_votes`.
<!--
BEGIN QUESTION
name: q2_4
-->

In [42]:
primary_total_votes = Table.read_table("primary_results.csv").column('sum_total_votes')


Ollis_votes = primary_total_votes.item(len(primary_total_votes) - 1)
Ollis_votes

834

**Question 2.5.** The 813th, 814th, and 815th rows of the `primary_results` table show the contest, names, and votes for the three people who were running for the position of Orange County Board of Commissioners At-Large in 2018. Assign `sum_of_OC_votes` to the sum of votes for these three people using the `primary_total_votes` array.

<!--
BEGIN QUESTION
name: q2_5
-->

In [44]:
sum_of_OC_votes = primary_total_votes.item(812) + primary_total_votes.item(813) + primary_total_votes.item(814)
sum_of_OC_votes

18192

## 3. Basic Array Arithmetic


**Question 3.1.** Multiply the numbers 12, 1212, 122122, and -120 by 585. Assign each variable below such that `first_product` is assigned to the result of $12 * 585$, `second_product` is assigned to the result of $1212 * 585$, and so on. 

For this question, **don't** use arrays.

<!--
BEGIN QUESTION
name: q3_1
-->

In [54]:
first_product = 12*585
second_product = 1212*585
third_product = 122122*585
fourth_product = -120*585
print(first_product, second_product, third_product, fourth_product)

7020 709020 71441370 -70200


**Question 3.2.** Now, do the same calculation, but using an array called `numbers` and only a single multiplication (`*`) operator.  Store the 4 results in an array named `products`.

<!--
BEGIN QUESTION
name: q3_2
-->

In [58]:
numbers = make_array(12, 1212, 122122, -120)
products = numbers*585
products

array([    7020,   709020, 71441370,   -70200])

**Question 3.3.** Oops, we made a typo!  Instead of 585, we wanted to multiply each number by 919.  Compute the correct products in the cell below using array arithmetic.  Notice that your job is really easy if you previously defined an array containing the 4 numbers.

<!--
BEGIN QUESTION
name: q3_3
-->

In [60]:
correct_products = numbers * 919
correct_products

array([    11028,   1113828, 112230118,   -110280])

**Question 3.4.** We've loaded an array of temperatures in the next cell. This dataset contains air quality data collected using a PurpleAir Dual Laser Air Quality Sensor located at the Chapel Hill Public Library, as well as temperature in Fahrenheit. Convert the temperatures to Celsius by first subtracting 32 from them, then multiplying the results by $\frac{5}{9}$. Make sure to **ROUND** the final result after converting to Celsius to the nearest integer using the `np.round` function.

<!--
BEGIN QUESTION
name: q3_4
-->

In [68]:
temperatures = Table.read_table("Local_Air_Quality.csv").column("Temp_F")

celsius_temperatures = np.round((temperatures - 32) * (5/9))
celsius_temperatures

array([ 31.,  31.,  30., ...,  21.,  21.,  23.])

## 4. North Carolina Population


The cell below loads a table of estimates of the North Carolina population from 1900 to 2021. The estimates come from the [FRED Economic Data](https://fred.stlouisfed.org/series/NCPOP).

In [70]:
NCpop = Table.read_table("NCpop.csv")
NCpop.show(4)

The name `population` is assigned to an array of population estimates.

In [72]:
population = NCpop.column(1)
population

array([ 1897000,  1926000,  1956000,  1986000,  2017000,  2051000,
        2077000,  2105000,  2142000,  2174000,  2221000,  2276000,
        2313000,  2362000,  2421000,  2473000,  2513000,  2546000,
        2522000,  2535000,  2588000,  2651000,  2700000,  2761000,
        2830000,  2895000,  2959000,  3027000,  3082000,  3133000,
        3167000,  3184000,  3227000,  3268000,  3304000,  3323000,
        3346000,  3385000,  3440000,  3514000,  3574000,  3589000,
        3569000,  3654000,  3560000,  3533000,  3706000,  3769000,
        3837000,  3911000,  4068000,  4120000,  4109000,  4120000,
        4131000,  4242000,  4309000,  4368000,  4376000,  4458000,
        4573000,  4663000,  4707000,  4742000,  4802000,  4863000,
        4896000,  4952000,  5004000,  5031000,  5084411,  5203531,
        5301150,  5389852,  5470911,  5547188,  5607964,  5685607,
        5759492,  5823491,  5898980,  5956653,  6019101,  6077056,
        6164006,  6253954,  6321578,  6403700,  6480594,  6565

In this question, you will apply some built-in Numpy functions to this array. Numpy is a module that is often used in Data Science!

The difference function `np.diff` subtracts each element in an array from the element after it within the array. As a result, the length of the array `np.diff` returns will always be one less than the length of the input array.

The cumulative sum function `np.cumsum` outputs an array of partial sums. For example, the third element in the output array corresponds to the sum of the first, second, and third elements.

**Question 4.1.** Very often in data science, we are interested understanding how values change with time. Use `np.diff` (and other functions) to calculate the largest absolute change (positive or negative) in population between any two consecutive years.

<!--
BEGIN QUESTION
name: q4_1
-->

In [84]:
largest_change_NC_pop = np.max(np.abs(np.diff(population)))
largest_change_NC_pop

430825

**Question 4.2.** What do the values in the resulting array represent (choose one)?

In [86]:
np.cumsum(np.diff(population))

array([  29000,   59000,   89000,  120000,  154000,  180000,  208000,
        245000,  277000,  324000,  379000,  416000,  465000,  524000,
        576000,  616000,  649000,  625000,  638000,  691000,  754000,
        803000,  864000,  933000,  998000, 1062000, 1130000, 1185000,
       1236000, 1270000, 1287000, 1330000, 1371000, 1407000, 1426000,
       1449000, 1488000, 1543000, 1617000, 1677000, 1692000, 1672000,
       1757000, 1663000, 1636000, 1809000, 1872000, 1940000, 2014000,
       2171000, 2223000, 2212000, 2223000, 2234000, 2345000, 2412000,
       2471000, 2479000, 2561000, 2676000, 2766000, 2810000, 2845000,
       2905000, 2966000, 2999000, 3055000, 3107000, 3134000, 3187411,
       3306531, 3404150, 3492852, 3573911, 3650188, 3710964, 3788607,
       3862492, 3926491, 4001980, 4059653, 4122101, 4180056, 4267006,
       4356954, 4424578, 4506700, 4583594, 4668459, 4759987, 4851135,
       4934850, 5050412, 5163959, 5288403, 5410658, 5531672, 5648828,
       5753789, 6184

1) The total population change between consecutive years, starting at 1901.

2) The total population change between 1900 and each later year, starting at 1901.

3) The total population change between 1900 and each later year, starting inclusively at 1900.

<!--
BEGIN QUESTION
name: q4_3
-->

In [88]:
# Assign cumulative_sum_answer to 1, 2, or 3
cumulative_sum_answer = 2

**Question 4.3.** Assign the name `smallest` to the smallest absolute (positive or negative) change in population between any two consecutive years. Assign the name `average` to the average of the changes in population between any two consecutive years. Consider that the change in population between years could be positive or negative and do not use the absolute changes when determining this average.

<!--
BEGIN QUESTION
name: q4_3
-->

In [156]:
smallest = np.min(np.abs(np.diff(population)))
average = np.abs(np.mean(np.diff(population)))


smallest, round(average)

(8000, 71522)

**Question 4.4.** Suppose that you had expected that the North Carolina population would have increased linearly by the average change each year (calculated in the previous problem). Set `difference_from_expected` to an array with 121 elements, where the elements are the differences (in order by years) between the actual population change during each pair of consectutive years (which could be positive or negative) and the expected change (`average`). 

For example, since the North Carolina populations in 1900 and 1901 are 1897000 and 1926000, the first element of the `difference_from_expected` would be  $(1926000 - 1897000) - average$

<!--
BEGIN QUESTION
name: q4_4
-->

In [158]:
difference_from_expected = np.diff(population) - average
difference_from_expected

array([ -42522.,  -41522.,  -41522.,  -40522.,  -37522.,  -45522.,
        -43522.,  -34522.,  -39522.,  -24522.,  -16522.,  -34522.,
        -22522.,  -12522.,  -19522.,  -31522.,  -38522.,  -95522.,
        -58522.,  -18522.,   -8522.,  -22522.,  -10522.,   -2522.,
         -6522.,   -7522.,   -3522.,  -16522.,  -20522.,  -37522.,
        -54522.,  -28522.,  -30522.,  -35522.,  -52522.,  -48522.,
        -32522.,  -16522.,    2478.,  -11522.,  -56522.,  -91522.,
         13478., -165522.,  -98522.,  101478.,   -8522.,   -3522.,
          2478.,   85478.,  -19522.,  -82522.,  -60522.,  -60522.,
         39478.,   -4522.,  -12522.,  -63522.,   10478.,   43478.,
         18478.,  -27522.,  -36522.,  -11522.,  -10522.,  -38522.,
        -15522.,  -19522.,  -44522.,  -18111.,   47598.,   26097.,
         17180.,    9537.,    4755.,  -10746.,    6121.,    2363.,
         -7523.,    3967.,  -13849.,   -9074.,  -13567.,   15428.,
         18426.,   -3898.,   10600.,    5372.,   13343.,   200

**Question 4.5.** Using the `difference_from_expected` array from the previous problem, At the begining of what year is the expected population change (assuming a linear increase in population by the average change) the most different (in magnitude - positive or negative) than the actual North Carolina population change over the prior year? 

<!--
BEGIN QUESTION
name: q5_4
-->

In [160]:
most_different = max(abs(difference_from_expected))
diff_year = 1901
most_different

359303.0

## 5. Tables


**Question 5.1.** Suppose that a Girl Scout is selling cookies and has 14 boxes of thin mints, 8 boxes of Samoas, 17 boxes of tagalongs, and 3 boxes of S'mores. Create a table that contains this information. It should have two columns: `cookie name` and `count`.  Assign the new table to the variable `gs_cookies`.

<!--
BEGIN QUESTION
name: q5_1
-->

In [124]:
# Our solution uses 1 statement split over 3 lines.
gs_cookies = Table().with_columns("cookie name", make_array("Thin Mints", "Samoas", "Tagalongs", "S'mores")).with_columns("count", make_array(14,8,17,3))

gs_cookies

cookie name | count
Thin Mints  | 14
Samoas      | 8
Tagalongs   | 17
S'mores     | 3

**Question 5.2.** The file `gs_inventory.csv` contains information about the cookie inventory of a  Girl Scout troop.  Each row represents the contents of one container of boxes of cookies. Load it as a table named `gs_inventory` using the `Table.read_table()` function. `Table.read_table(...)` takes one argument (data file name in string format) and returns a table.

<!--
BEGIN QUESTION
name: q5_2
-->

In [126]:
gs_inventory = Table.read_table("gs_inventory.csv")
gs_inventory

box ID | cookie name   | count
53686  | samoas        | 45
57181  | tagalongs     | 123
25274  | s'mores       | 20
48800  | do-si-dos     | 35
26187  | trefoils      | 255
57930  | thin mints    | 517
52357  | lemon-ups     | 102
43566  | toffee-tastic | 40
26778  | samoas        | 226

**Question 5.3.** Does each container contain a different type of cookie? Set `all_different` to `True` if each container contains a different type of cookie or to `False` if multiple containers contain the same cookie.

*Hint:* You don't have to write code to calculate the True/False value for `all_different`. Just look at the `gs_inventory` table and assign `all_different` to either `True` or `False` according to what you can see from the table in answering the question.

<!--
BEGIN QUESTION
name: q5_3
-->

In [128]:
all_different = False
all_different

False

**Question 5.4.** The file `gs_sales.csv` contains the number of boxes of cookies sold from each container over the previous weekend.  It has an extra column called "price per box (\$)" that's the price *per box of cookies* for the cookies in that container.  The rows are in the same order as the `gs_inventory` table.  Load these data into a table called `gs_sales`.

<!--
BEGIN QUESTION
name: q5_4
-->

In [130]:
gs_sales = Table().read_table("gs_sales.csv")
gs_sales

box ID | cookie name   | count sold | price per box ($)
53686  | samoas        | 22         | 5
57181  | tagalongs     | 47         | 5
25274  | s'mores       | 12         | 6
48800  | do-si-dos     | 11         | 5
26187  | trefoils      | 106        | 5
57930  | thin mints    | 312        | 5
52357  | lemon-ups     | 25         | 5
43566  | toffee-tastic | 9          | 6
26778  | samoas        | 99         | 5

**Question 5.5.** How many boxes of cookies did the troop sell in total over that weekend?

<!--
BEGIN QUESTION
name: q5_5
-->

In [134]:
total_cookies_sold = sum(gs_sales.column("count sold"))
total_cookies_sold

643

**Question 5.6.** What was the troops's total revenue (the total price of all boxes of cookies sold) over that weekend?

<!--
BEGIN QUESTION
name: q5_6
-->

In [136]:
total_revenue = total_cookies_sold * 5
total_revenue

3215

**Question 5.7.** Make a new table called `gs_remaining_inventory`.  It should have the same rows and columns as `gs_inventory`, except that the amount of boxes of cookies sold from each container should be subtracted from that container's count, so that the "count" is the amount of boxes of cookies remaining after that weekend.

<!--
BEGIN QUESTION
name: q5_7
-->

In [152]:
new_inventory = gs_inventory.column("count") - gs_sales.column("count sold")
gs_remaining_inventory = gs_inventory.with_column("count", new_inventory)

gs_remaining_inventory

box ID | cookie name   | count
53686  | samoas        | 23
57181  | tagalongs     | 76
25274  | s'mores       | 8
48800  | do-si-dos     | 24
26187  | trefoils      | 149
57930  | thin mints    | 205
52357  | lemon-ups     | 77
43566  | toffee-tastic | 31
26778  | samoas        | 127